 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:9.10.1
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
       - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       - run:
          name: install-npm-wee
          command: npm install
       - run: # run tests
          name: test
          command: npm test